name: manual-build-and-tag

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        type: string
        required: true
        default: 'master'
      tag:
        description: 'Tag to build and push to gcr.io'
        type: string
        required: true
        default: 'dev'
      name:
        description: 'Name for build and push to gcr.io'
        type: string
        required: true
        default: 'mcp-log-viewer-expirement'

jobs:
  call-build-and-tag:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-tag.yml
    with:
      GCR_NAME: ${{ inputs.name }}
      GCR_TAG: ${{ inputs.tag }}
      GITHUB_REF: ${{ inputs.branch }}
    secrets:
      GCR_SERVICE_ACCOUNT_KEY: ${{ secrets.GCR_SERVICE_ACCOUNT_KEY }}
